controller_manager:
  ros__parameters:
    update_rate: 50

basic_diff_drive:
  ros__parameters:
    type: "diff_drive_controller/DiffDriveController"
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]
    wheel_separation: 0.287
    wheel_radius: 0.033
    cmd_vel_timeout: 0.5
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0, 0, 0.001]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0, 0, 0.001]
