# turtlebot3_controller/config/diff_controllers.yaml
controller_manager:
  ros__parameters:
    update_rate: 50

diff_controller:
  ros__parameters:
    type: "diff_drive_controller/DiffDriveController"
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]
    wheel_separation: 0.160
    wheel_radius: 0.033
    cmd_vel_timeout: 0.5
    use_stamped_vel: false
    # ... 필요시 더 튜닝
